# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30)),
                ('releasedate', models.DateField()),
                ('heroname', models.CharField(max_length=30)),
                ('heroinename', models.CharField(max_length=30)),
                ('rating', models.IntegerField(max_length=30)),
            ],
        ),
    ]
